### ISSUE TITLE
MILESTONE: release v1.0.0

### ISSUE THREAD

**Issue by jkowalleck** [package-url/packageurl-php#5]
Hello @stevespringett 

the implementation is feature complete according to current specs.
it could be tagged/released as version 1.0.0

therefore the following is still needed:
- [x] have a build/release process in place
- [x] change install instructions in the  `README.md` to:
  ```markdown
  ## Install
  `composer require package-url/packageurl-php`
  ```
- [x] rename `HIStORY.md` to `HISTORY.md` - #4
- [x] modify the `HISTORY.md` accordingly, replace "unreleased" with "1.0.0"
- [x] tag version 1.0.0

did i forget something?

**Comment by stevespringett** [comment]
I'm not seeing `test-suite-data.json` in the repo. This will need to be in place along with the execution of the tests.

**Comment by stevespringett** [comment]
Scratch that. Found it. The list above looks good.

**Comment by stevespringett** [comment]
1.0.0 released to packagist
